"""Minor revamp

Revision ID: 588f281d0cb4
Revises: ecebed5c4c7e
Create Date: 2026-03-24 15:43:23.538592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588f281d0cb4'
down_revision: Union[str, Sequence[str], None] = 'ecebed5c4c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('version_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'version_count')
    # ### end Alembic commands ###
